version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    container_name: vtes-mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=AdminDef
      - MYSQL_DATABASE=vtes
    volumes:
      - ./vtesdb:/docker-entrypoint-initdb.d:ro
      - mysql-vtes-data:/var/lib/mysql
      - mysql-config:/etc/mysql/conf.d
    networks:
      - backend
  app:
    build: .
    container_name: vtes-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  mysql-vtes-data:
  mysql-config:
  vtesdb:
