apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtes-app
spec:
  replicas: 1
  serviceName: vtes-app
  selector:
    matchLabels:
      app: vtes-app
  template:
    metadata:
      labels:
        app: vtes-app
    spec:
    nodeSelector:
      "kubernetes.io/os": linux
      containers:
      - name: vtes-app
        image: chienvti.azurecr.io/vtes/vtes-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: AdminDef
        - name: MYSQL_DATABASE
          value: vtes
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vtes-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: vtes-app
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtes-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtes-redis
  template:
    metadata:
      labels:
        app: vtes-redis
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      serviceName: vtes-redis
      containers:
      - name: vtes-redis
        image: redis
        resources:
          limits:
            memory: "10Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data-volume
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis-config
      volumes:
      - name: redis-data-volume
        configMap:
          - key: redis.conf
            path: redis-config
---
apiVersion: v1
kind: ConfigMap
data:
  redis.conf: |
    port 6379
    maxmemory 500mb
    maxmemory-policy allkeys-lfu
    requirepass vtes2023
metadata:
  name: redis-config

---
apiVersion: apps/v1
kind: Service
metadata:
  name: vtes-redis
  spec:
    selector:
      app: vtes-redis
    ports:
    - name: redis
      port: 6379
      targetPort: 6379
    type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtes-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtes-mysql
  template:
    metadata:
      labels:
        app: vtes-mysql
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: vtes-mysql
        image: mysql
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data-volume
          mountPath: /mysql-data
      volumes:

---
apiVersion: v1
kind: Service
metadata:
  name: vtes-mysql
spec:
  selector:
    app: vtes-mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  type: ClusterIP
